SELECT ID_BIEN,DESCRIPCION,PRECIO,ESTADO,ID_CLASEBIEN,ID_EMPRESA FROM [dbo].[BIEN] WHERE ID_BIEN = 'B00003'
SELECT ID_BIEN,DESCRIPCION,PRECIO,ESTADO,ID_CLASEBIEN,ID_EMPRESA FROM [dbo].[BIEN] WHERE ID_BIEN = 'B00005'

