


CREATE PROC SP_ENTRADAS
@ID_TIPOBIEN CHAR(2),
@BIEN VARCHAR(100)
AS
SELECT ID_BIEN,DESCRIPCION,PRECIO
FROM BIEN
WHERE ID_TIPOBIEN =  @ID_TIPOBIEN AND DESCRIPCION LIKE '%'+@BIEN+'%'
GO

--------------------------------------------------------------------------------------------------------------------------------------



CREATE PROC SP_VALIDAR_LOG_WEB --'37654223','KVEGA','001'
@DNI_USUARIO CHAR(8),
@CONTRASENA VARCHAR(20)
AS
SELECT DNI_USUARIO,CONTRASENA,DESCRIPCION AS USUARIO
FROM USUARIO_WEB
WHERE DNI_USUARIO = @DNI_USUARIO AND CONTRASENA = @CONTRASENA 

GO
---------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE USER_WEB(
	[ID_USUARIO] [char](5) NOT NULL,
	[CONTRASENA] [varchar](20) NOT NULL,
	[RUC_DNI] [varchar](8) NOT NULL,
	[DESCRIPCION] [varchar](100) NULL,
	[TELEFONO] [varchar](50) NULL,
	[EMAIL] [varchar](100) NULL,
	[ESTADO] [bit] NULL,
	[TIPO_USUARIO] [char](2) NULL,
	[UBIDST] [varchar](6) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[RUC_DNI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[USER_WEB]  WITH CHECK ADD  CONSTRAINT [FK_USER_UBIGEO] FOREIGN KEY([UBIDST])
REFERENCES [dbo].[UBIGEO] ([UBIDST])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[USER_WEB] CHECK CONSTRAINT [FK_USER_UBIGEO]
GO



-------------------------------------------------------------------------------------------------------------------------------------------



CREATE PROC SP_GRABAR_PEDIDO_WEB 
@ID_PEDIDO CHAR(10) OUTPUT, /* ESTO ME DEVUELVE EL ID_PEDIDO */
@ID_USUARIO CHAR(5),
@CLIENTE VARCHAR(20),
@VALOR_VENTA DECIMAL(8,2),
@IGV DECIMAL(8,2),
@TOTAL DECIMAL(8,2),
@MONEDA CHAR(1),
@OBSERVACION VARCHAR(250),
@FECHA DATETIME,
@ID_SEDE CHAR(3),
@ACCION CHAR(1)
AS

IF @ACCION=2
   BEGIN
     UPDATE PEDIDO 
	 SET ID_PEDIDO=@ID_PEDIDO,ID_EMPLEADO=@ID_USUARIO,FECHA=@FECHA,CLIENTE=@CLIENTE,VALOR_VENTA=@VALOR_VENTA,IGV=@IGV,
				TOTAL=@TOTAL,MONEDA=@MONEDA,OBSERVACION=@OBSERVACION
     WHERE ID_PEDIDO=@ID_PEDIDO   
   END


GO

